extension Level {
    /// The whole campaign: the handmade opening levels, then the generated ones.
    public static let campaign: [Level] = handmade + LevelGenerator.levels

    /// The handmade opening levels. Layout legend: see `Level`.
    static let handmade: [Level] = [
        Level(id: 1, name: "Erster Bissen", moves: 20, colors: 5,
              goals: [.score(2_500)], starScores: [2_500, 20_000, 34_000],
              layout: [
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
              ]),
        Level(id: 2, name: "Ruhige Hand", moves: 16, colors: 5,
              goals: [.score(5_000)], starScores: [5_000, 13_000, 18_000],
              layout: [
                  "##.....##",
                  "#.......#",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  "#.......#",
                  "##.....##",
              ]),
        Level(id: 3, name: "Gelee", moves: 22, colors: 5,
              goals: [.clearJelly], starScores: [3_000, 19_000, 27_000],
              layout: [
                  ".........",
                  ".........",
                  "..jjjjj..",
                  "..jjjjj..",
                  "..jjjjj..",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
              ]),
        Level(id: 4, name: "Kirschernte", moves: 25, colors: 5,
              goals: [.collectIngredients(2)], starScores: [3_000, 24_000, 35_000],
              layout: [
                  "....i....",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
              ]),
        Level(id: 5, name: "Gitter", moves: 24, colors: 5,
              goals: [.clearJelly], starScores: [4_000, 20_000, 35_000],
              layout: [
                  ".........",
                  ".........",
                  "..lllll..",
                  ".jjjjjjj.",
                  ".jjkkkjj.",
                  ".jjjjjjj.",
                  "..lllll..",
                  ".........",
                  ".........",
              ]),
        Level(id: 6, name: "Zuckerwürfel", moves: 18, colors: 5,
              goals: [.score(9_000)], starScores: [9_000, 15_000, 24_000],
              layout: [
                  ".........",
                  ".........",
                  ".........",
                  "b.b.b.b.b",
                  ".........",
                  ".........",
                  "..BbBbB..",
                  ".........",
                  ".........",
              ]),
        Level(id: 7, name: "Schokolade", moves: 25, colors: 5,
              goals: [.clearChocolate, .clearJelly], starScores: [5_000, 22_000, 34_000],
              layout: [
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  ".........",
                  "..jjjjj..",
                  "cc.jjj.cc",
                  "ccjjjjjcc",
                  "ccc...ccc",
              ]),
        Level(id: 8, name: "Sanduhr", moves: 28, colors: 5,
              goals: [.clearJelly], starScores: [6_000, 16_000, 22_000],
              layout: [
                  "jjjjjjjjj",
                  "#jjjjjjj#",
                  "##jjjjj##",
                  "###jjj###",
                  "###j.j###",
                  "###jjj###",
                  "##jjjjj##",
                  "#jjjjjjj#",
                  "jjjjjjjjj",
              ]),
        Level(id: 9, name: "Nussknacker", moves: 30, colors: 5,
              goals: [.collectIngredients(3)], starScores: [6_000, 29_000, 39_000],
              layout: [
                  "..h...i..",
                  ".........",
                  ".........",
                  ".........",
                  "b.......b",
                  ".........",
                  "..c...c..",
                  ".........",
                  ".........",
              ], maxIngredientsOnBoard: 2),
        Level(id: 10, name: "Doppelschicht", moves: 25, colors: 5,
              goals: [.clearJelly, .score(15_000)], starScores: [15_000, 24_000, 43_000],
              layout: [
                  ".........",
                  ".........",
                  "JJ.....JJ",
                  "JJb...bJJ",
                  ".........",
                  "JJb...bJJ",
                  "JJ.....JJ",
                  ".........",
                  ".........",
              ]),
        Level(id: 11, name: "Gefangen", moves: 32, colors: 6,
              goals: [.clearJelly], starScores: [8_000, 19_000, 27_000],
              layout: [
                  ".........",
                  ".........",
                  "kk.....kk",
                  "kkjjjjjkk",
                  "..jjjjj..",
                  "kkjjjjjkk",
                  "kk.....kk",
                  ".........",
                  ".........",
              ]),
        Level(id: 12, name: "Lagom", moves: 34, colors: 6,
              goals: [.clearChocolate, .collectIngredients(2)], starScores: [10_000, 15_000, 20_000],
              layout: [
                  "###.i.###",
                  "##.....##",
                  "#.......#",
                  ".........",
                  "....c....",
                  "...ccc...",
                  "..jcccj..",
                  "..jjjjj..",
                  "..jjjjj..",
              ]),
    ]
}
