import AVFoundation
import Match3Core

/// Sound effects, background music and the combo voice.
///
/// Effects are short WAV files in `App/Sounds` (generated by `scripts/make_sounds.py`). They play
/// through a small pool of engine players with varispeed, so cascades can climb in pitch.
@MainActor
final class SoundManager {
    static let shared = SoundManager()

    enum Effect: String, CaseIterable {
        case swap, pop, crunch, stripe, bomb, colorbomb, special, fish, invalid, collect, star, tap, jelly
        case win, lose, sugarrush, whoosh
    }

    private let engine = AVAudioEngine()
    private var voices: [(player: AVAudioPlayerNode, speed: AVAudioUnitVarispeed)] = []
    private var nextVoice = 0
    private var buffers: [Effect: AVAudioPCMBuffer] = [:]
    private var format: AVAudioFormat?
    private var music: AVAudioPlayer?
    private let speech = AVSpeechSynthesizer()
    private var isConfigured = false
    private var lastPlayed: [Effect: TimeInterval] = [:]

    private var soundOn: Bool { UserDefaults.standard.bool(forKey: SettingsKey.sound) }
    private var voiceOn: Bool { UserDefaults.standard.bool(forKey: SettingsKey.voice) }
    private var musicOn: Bool { UserDefaults.standard.bool(forKey: SettingsKey.music) }

    private init() {}

    // MARK: Effects

    /// `pitch` > 1 raises the sound (and makes it a little shorter); cascades use it to climb.
    func play(_ effect: Effect, pitch: Double = 1, volume: Float = 1) {
        guard soundOn, prepareEngine(), let buffer = buffers[effect] else { return }
        // The same sound many times in one frame only gets louder, not nicer.
        let now = ProcessInfo.processInfo.systemUptime
        if let last = lastPlayed[effect], now - last < 0.03 { return }
        lastPlayed[effect] = now

        let voice = voices[nextVoice]
        nextVoice = (nextVoice + 1) % voices.count
        voice.player.stop()
        voice.speed.rate = Float(min(2.5, max(0.5, pitch)))
        voice.player.volume = volume
        voice.player.scheduleBuffer(buffer, at: nil, options: [], completionHandler: nil)
        voice.player.play()
    }

    /// Plays a UI click.
    func tap() { play(.tap, volume: 0.7) }

    // MARK: Music

    /// Starts or stops the background loop to match the setting.
    func updateMusic() {
        guard musicOn else {
            music?.pause()
            return
        }
        configureSession()
        if music == nil, let url = Bundle.main.url(forResource: "music", withExtension: "m4a") {
            music = try? AVAudioPlayer(contentsOf: url)
            music?.numberOfLoops = -1
            music?.volume = 0.32
            music?.prepareToPlay()
        }
        if music?.isPlaying == false { music?.play() }
    }

    /// Stops the music when leaving the Bonbon-Puzzle; the other games play without it.
    func stopMusic() {
        music?.pause()
    }

    /// Dims the music under the results screen and brings it back afterwards.
    func duckMusic(_ ducked: Bool) {
        music?.setVolume(ducked ? 0.12 : 0.32, fadeDuration: 0.4)
    }

    // MARK: Voice

    /// Deep voice for combo chains ("Delicious!", "Divine!").
    func say(_ text: String) {
        guard voiceOn else { return }
        let utterance = AVSpeechUtterance(string: text.replacingOccurrences(of: "!", with: ""))
        utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
        utterance.pitchMultiplier = 0.6
        utterance.rate = 0.42
        utterance.volume = 0.9
        speech.stopSpeaking(at: .immediate)
        speech.speak(utterance)
    }

    func say(_ word: ComboWord) { say(word.rawValue) }

    // MARK: Engine

    private func configureSession() {
        try? AVAudioSession.sharedInstance().setCategory(.ambient, options: [.mixWithOthers])
        try? AVAudioSession.sharedInstance().setActive(true)
    }

    private func prepareEngine() -> Bool {
        if !isConfigured {
            isConfigured = true
            configureSession()
            for effect in Effect.allCases {
                guard let url = Bundle.main.url(forResource: effect.rawValue, withExtension: "wav"),
                      let file = try? AVAudioFile(forReading: url),
                      let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat,
                                                    frameCapacity: AVAudioFrameCount(file.length)),
                      (try? file.read(into: buffer)) != nil else { continue }
                buffers[effect] = buffer
                format = format ?? file.processingFormat
            }
            guard let format else { return false }
            for _ in 0..<12 {
                let player = AVAudioPlayerNode()
                let speed = AVAudioUnitVarispeed()
                engine.attach(player)
                engine.attach(speed)
                engine.connect(player, to: speed, format: format)
                engine.connect(speed, to: engine.mainMixerNode, format: format)
                voices.append((player, speed))
            }
            engine.mainMixerNode.outputVolume = 0.9
        }
        guard !voices.isEmpty else { return false }
        if !engine.isRunning {
            do { try engine.start() } catch { return false }
        }
        return true
    }
}
